/* 真实浏览器回归；数据只写入本测试创建的临时目录。 */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const net=require('node:net');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
fs.mkdirSync(path.join(root,'artifacts','ui-validation'),{recursive:true});
const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'sync-ui-')));
const browseFixture=path.join(temp,'目录浏览');fs.mkdirSync(browseFixture);
for(let i=205;i>=1;i--){const d=path.join(browseFixture,`目录${i}`);fs.mkdirSync(d);fs.utimesSync(d,1000+i,1000+i)}
fs.mkdirSync(path.join(browseFixture,'REPORT'));
const source=path.join(temp,'工作资料');fs.mkdirSync(source);
for(let i=0;i<510;i++)fs.writeFileSync(path.join(source,`资料-${i}.txt`),'文件同步界面测试');
fs.symlinkSync('资料-0.txt',path.join(source,'链接示例'));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p))})});
 const base=`http://127.0.0.1:${port}`;
 const python=process.env.SYNC_TEST_PYTHON||path.join(root,'.venv-standalone',process.platform==='win32'?'Scripts':'bin',process.platform==='win32'?'python.exe':'python');
 const server=spawn(python,['-c',"import sys;sys.path.insert(0,'backend');from standalone.api import create_app;import uvicorn;uvicorn.run(create_app(sys.argv[1]),host='127.0.0.1',port=int(sys.argv[2]),log_level='error')",path.join(temp,'state','db.sqlite3'),String(port)],{cwd:root,stdio:['ignore','ignore','pipe']});
 let serverErrors='';server.stderr.on('data',data=>serverErrors+=data);
 let browser;
 try{
  let ready=false;for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok){ready=true;break}}catch{}await delay(100)}assert(ready,serverErrors);
  const request=async(url,body)=>{const r=await fetch(base+'/api'+url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Sync-Local':'1'},body:body?JSON.stringify(body):undefined});assert(r.ok,await r.clone().text());return r.json()};
  for(let i=0;i<11;i++)await request('/tasks',{name:`归档任务 ${String(i+1).padStart(2,'0')}`,source,target:path.join(temp,'backup-'+i)});
  browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  // 延迟初始目录响应，验证它不会覆盖随后输入的新地址。
  await page.route('**/api/directories?*',async route=>{if(!new URL(route.request().url()).searchParams.get('path'))await delay(250);await route.continue()});
  console.log('检查列表与菜单');await page.goto(base);await page.waitForFunction(()=>document.querySelector('#taskCount').textContent==='11');
  assert.equal(await page.locator('#tasks tr').count(),10);
  await page.locator('#taskPager').getByRole('button',{name:'下一页'}).click();assert.equal(await page.locator('#tasks tr').count(),1);
  await page.locator('#taskSearch').fill('归档任务 03');assert.equal(await page.locator('#tasks tr').count(),1);
  await page.locator('#tasks summary').click();await delay(2200);assert(await page.locator('#tasks details').getAttribute('open')!==null);
  await page.keyboard.press('Escape');await page.locator('#taskSearch').fill('');
  await page.getByRole('button',{name:'＋ 新建任务',exact:true}).click();
  await page.locator('input[name=name]').fill('工作资料备份');
  await page.locator('#mappings').getByRole('button',{name:'浏览'}).first().click();
  console.log('检查目录搜索和排序');await page.locator('#folderAddress').fill(browseFixture);await page.locator('#folderGo').click();
  await page.waitForFunction(()=>document.querySelector('#folderCount').textContent.includes('206'));
  assert.equal(await page.locator('#folderList button').count(),200);
  await page.locator('#folderMore').click();await page.waitForFunction(()=>document.querySelectorAll('#folderList button').length===206);
  await page.locator('#folderSearch').fill('目录205');await page.waitForFunction(()=>document.querySelector('#folderCount').textContent.includes('匹配 1 '));
  assert.equal(await page.locator('#folderList button').first().textContent(),'目录205');
  await page.locator('#folderSearch').fill('report');await page.waitForFunction(()=>document.querySelector('#folderList').textContent==='REPORT');
  await page.locator('#folderSearch').fill('不存在');await page.waitForFunction(()=>document.querySelector('#folderCount').textContent.includes('匹配 0 '));
  assert(!(await page.locator('#folderSelect').isDisabled()));
  await page.locator('#folderClear').click();await page.waitForFunction(()=>document.querySelectorAll('#folderList button').length===200);
  await page.locator('#folderSearch').fill('目录');await page.locator('#folderSort').selectOption('name_desc');await page.waitForFunction(()=>document.querySelector('#folderList button')?.textContent==='目录205');
  await page.locator('#folderSort').selectOption('modified_asc');await page.waitForFunction(()=>document.querySelector('#folderList button')?.textContent.startsWith('目录1'));
  assert.equal((await page.locator('#folderList button').first().textContent()).split('1970')[0],'目录1');
  await page.locator('#folderSort').selectOption('name_asc');await page.waitForFunction(()=>document.querySelector('#folderList button')?.textContent==='目录1');
  await page.locator('#folderList button').first().click();await page.waitForFunction(()=>document.querySelector('#currentFolder').textContent.endsWith('/目录1'));
  assert.equal(await page.locator('#folderSearch').inputValue(),'');
  await page.locator('#folderUp').click();await page.waitForFunction(()=>document.querySelector('#folderCount').textContent.includes('206'));
  const browseArtifacts=path.join(root,'artifacts','ui-validation');fs.mkdirSync(browseArtifacts,{recursive:true});
  await page.screenshot({path:path.join(browseArtifacts,'directory-browser.png'),fullPage:false});
  console.log('检查目录浏览');await page.locator('#folderAddress').fill(source);await page.locator('#folderGo').click();await page.waitForFunction(()=>!document.querySelector('#folderSelect').disabled);
  await page.locator('#folderSelect').click();assert.equal(await page.locator('[data-path=source]').inputValue(),source);
  await page.locator('[data-path=target]').fill(path.join(temp,'实际备份'));
  await page.locator('#addMapping').click();assert.equal(await page.locator('.mapping').count(),2);
  await page.locator('.mapping').last().getByRole('button',{name:'移除'}).click();
  // 离开未保存表单时可以取消，不丢失输入。
  page.once('dialog',dialog=>dialog.dismiss());await page.locator('#tab-tasks').click();assert(await page.locator('#panel-editor').isVisible());
  await page.locator('#rulePreset').selectOption('mirror');await page.locator('#applyPreset').click();assert(await page.locator('input[name=delete]').isChecked());
  await page.locator('#rulePreset').selectOption('merge');await page.locator('#applyPreset').click();assert.equal(await page.locator('#syncDirection').inputValue(),'bidirectional');assert(await page.locator('input[name=delete]').isDisabled());
  await page.locator('#rulePreset').selectOption('project');await page.locator('#applyPreset').click();assert((await page.locator('textarea[name=ignorePatterns]').inputValue()).includes('node_modules/'));assert(await page.locator('input[name=continueOnError]').isChecked());
  await page.locator('#rulePreset').selectOption('incremental');await page.locator('#applyPreset').click();assert(!(await page.locator('input[name=delete]').isChecked()));
  await page.locator('textarea[name=ignorePatterns]').fill('*.ignore');
  assert.equal(await page.locator('#comparisonMethod').inputValue(),'size');
  await page.locator('#comparisonMethod').selectOption('sha256');page.once('dialog',dialog=>dialog.accept());
  assert(await page.locator('input[name=skipUnsupported]').isChecked());await page.locator('input[name=skipUnsupported]').check();
  console.log('检查保存与演练');await page.locator('#saveTask').click();await page.waitForFunction(()=>document.querySelector('#taskCount').textContent==='12');
  await page.locator('#taskSearch').fill('工作资料备份');await page.locator('#tasks summary').click();
  await page.locator('#tasks').getByRole('button',{name:'演练',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#runs').textContent.includes('演练完成'));
  assert(!fs.existsSync(path.join(temp,'实际备份')));assert((await page.locator('#runs').textContent()).includes('已排除 1 个链接或特殊文件'));
  assert.equal((await request('/tasks')).find(t=>t.name==='工作资料备份').skipUnsupported,true);
  console.log('检查日志');await page.locator('#runs').getByRole('button',{name:'查看日志'}).first().click();await page.locator('#logPageSize').selectOption('500');await page.waitForFunction(()=>document.querySelectorAll('#logs tr').length===500);
  assert((await page.locator('#logOverview').textContent()).includes('演练日志'));assert((await page.locator('#logOverview').textContent()).includes('SHA-256'));
  await page.locator('#logNext').click();await page.waitForFunction(()=>document.querySelector('#logPageText').textContent.startsWith('第 2 /'));
  assert.equal(await page.locator('#logs tr').count(),14);
  assert((await page.locator('#logCount').textContent()).includes('514'));
  await page.locator('#logJump').fill('1');await page.locator('#logGo').click();
  await page.waitForFunction(()=>document.querySelector('#logPageText').textContent.startsWith('第 1 /'));
  await page.locator('#logAction').selectOption('mapping_completed');await page.waitForFunction(()=>document.querySelector('#logCount').textContent==='共 1 条匹配日志');
  assert.equal(await page.locator('#logs tr').count(),1);
  await page.locator('#runReport').getByRole('button',{name:'预计复制 510',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#logCount').textContent==='共 510 条匹配日志');
  assert.equal(await page.locator('#logAction').inputValue(),'copied');
  await page.locator('#logSearch').fill('资料-509.txt');
  await page.waitForFunction(()=>document.querySelector('#logCount').textContent==='共 1 条匹配日志');
  assert((await page.locator('#logs').textContent()).includes('资料-509.txt'));
  await page.screenshot({path:path.join(root,'artifacts','ui-validation','standalone-report.png'),fullPage:true});

  console.log('检查实际复制');await page.locator('#tab-tasks').click();page.once('dialog',dialog=>dialog.accept());
  await page.locator('#tasks').getByRole('button',{name:'运行',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#runs tr').textContent.includes('成功'));
  assert.equal((await request('/tasks')).find(t=>t.name==='工作资料备份').checksum,true);
  const saved=(await request('/tasks')).find(t=>t.name==='工作资料备份');
  assert.equal(saved.comparisonMode,'sha256');assert.equal(saved.preserveTime,true);assert.equal(saved.timeToleranceSeconds,2);
  const newestRun=(await request('/runs'))[0];const actualEvents=await request(`/runs/${newestRun.id}/events`);assert(actualEvents.some(e=>JSON.parse(e.detail).verification?.writtenSha256));
  assert.equal(fs.readFileSync(path.join(temp,'实际备份','资料-0.txt'),'utf8'),'文件同步界面测试');assert(!fs.existsSync(path.join(temp,'实际备份','链接示例')));
  await page.locator('#tab-tasks').click();await page.locator('#tasks summary').click();await page.locator('#tasks').getByRole('button',{name:'复制配置'}).click();assert.equal(await page.locator('input[name=name]').inputValue(),'工作资料备份（副本）');
  page.once('dialog',dialog=>dialog.accept());await page.locator('#cancelEdit').click();
  await page.locator('#tasks summary').click();page.once('dialog',dialog=>dialog.dismiss());await page.locator('#tasks').getByRole('button',{name:'删除任务'}).click();assert.equal((await request('/tasks')).length,12);
  // 从界面切换双向模式，直接运行（不先演练），验证反向复制及冲突保留。
  await page.locator('#tasks summary').click();await page.locator('#tasks').getByRole('button',{name:'编辑任务',exact:true}).click();
  assert.equal(await page.locator('textarea[name=ignorePatterns]').inputValue(),'*.ignore');
  await page.locator('#rulePreset').selectOption('merge');await page.locator('#applyPreset').click();await page.locator('input[name=skipUnsupported]').check();
  await page.locator('#saveTask').click();await page.waitForFunction(()=>!document.querySelector('#panel-tasks').hidden);
  fs.writeFileSync(path.join(temp,'实际备份','反向新增.txt'),'from right');fs.writeFileSync(path.join(temp,'实际备份','资料-0.txt'),'conflicting target');
  page.once('dialog',dialog=>dialog.accept());await page.locator('#tasks').getByRole('button',{name:'运行',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#runs tr').textContent.includes('部分完成'));
  assert.equal(fs.readFileSync(path.join(source,'反向新增.txt'),'utf8'),'from right');assert.equal(fs.readFileSync(path.join(source,'资料-0.txt'),'utf8'),'文件同步界面测试');
  assert((await page.locator('#runs tr').first().textContent()).includes('冲突 1'));
  await page.locator('#tab-tasks').click();
  // 保留截图验证宽屏列表和窄屏配置布局。
  const artifacts=path.join(root,'artifacts','ui-validation');fs.mkdirSync(artifacts,{recursive:true});
  await page.locator('#taskSearch').fill('');if(await page.locator('#taskPager').getByRole('button',{name:'上一页'}).isEnabled())await page.locator('#taskPager').getByRole('button',{name:'上一页'}).click();
  await page.screenshot({path:path.join(artifacts,'standalone-tasks.png'),fullPage:true});
  await page.getByRole('button',{name:'＋ 新建任务',exact:true}).click();await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:path.join(artifacts,'standalone-mobile-editor.png'),fullPage:true});
  await page.locator('[data-path=source]').fill(source);await page.locator('#mappings').getByRole('button',{name:'浏览'}).first().click();await page.waitForFunction(()=>!document.querySelector('#folderSelect').disabled);await page.keyboard.press('Escape');assert(!(await page.locator('#folderDialog').isVisible()));
  // 验证空筛选、Tab 键盘导航与首屏请求失败后的重试。
  page.once('dialog',dialog=>dialog.accept());await page.locator('#cancelEdit').click();
  await page.locator('#taskSearch').fill('不存在的任务xyz');assert((await page.locator('#tasks').textContent()).includes('没有符合条件'));
  await page.locator('#tab-tasks').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab-runs').getAttribute('aria-selected'),'true');
  let failOnce=true;await page.route('**/api/tasks',async route=>{if(failOnce){failOnce=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'模拟连接中断'})})}else await route.continue()});
  await page.reload();await page.getByRole('button',{name:'重试',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#taskCount').textContent==='12');assert(await page.locator('#message').isHidden());
  // 限速临时文件，让浏览器实际观察传输中的计数、速度和百分比。
  const liveSource=path.join(temp,'live-source');fs.mkdirSync(liveSource);fs.writeFileSync(path.join(liveSource,'large.bin'),Buffer.alloc(3*1024*1024,1));
  const liveTask=await request('/tasks',{name:'实时进度验证',source:liveSource,target:path.join(temp,'live-target'),parallelism:1,bandwidthLimit:256});
  await request(`/tasks/${liveTask.id}/run`,{dryRun:false});
  await page.locator('#tab-runs').click();
  await page.waitForFunction(()=>document.querySelector('#liveProgress').textContent.includes('写入临时文件：large.bin'));
  await page.locator('#tab-tasks').click();
  assert(await page.locator('#liveProgress').isVisible());
  assert.equal(await page.locator('.activity-stages [aria-current=step]').textContent(),'比较 / 复制 / 校验');
  assert.equal(await page.locator('.activity-spinner').evaluate(n=>getComputedStyle(n).animationName),'sync-spin');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.activity-spinner').evaluate(n=>getComputedStyle(n).animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  assert((await page.locator('#liveProgress').textContent()).includes('文件/秒'));
  assert((await page.locator('#liveProgress').textContent()).includes('本组文件处理'));
  assert(await page.locator('#liveProgress progress').count()>=1);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:path.join(artifacts,'standalone-live-progress.png'),fullPage:true});
  await page.route('**/api/runs',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'模拟进度连接失败'})}));
  await page.locator('#refreshTasks').click();
  await page.waitForFunction(()=>document.querySelector('#liveProgress').classList.contains('stale'));
  assert.equal(await page.locator('.activity-spinner').evaluate(n=>getComputedStyle(n).animationPlayState),'paused');
  await page.unroute('**/api/runs');await page.locator('#refreshTasks').click();
  await page.waitForFunction(()=>!document.querySelector('#liveProgress').classList.contains('stale'));
  await page.waitForFunction(()=>document.querySelector('#liveProgress').hidden);
  await page.locator('#tab-tasks').click();
  // 新网页对旧后台拒绝提交，避免 Pydantic 静默丢弃新字段。
  let unexpectedRuns=0;
  await page.route('**/api/health',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({mode:'standalone',version:1})}));
  await page.route('**/api/tasks/*/run',route=>{unexpectedRuns++;return route.abort()});
  await page.locator('#refreshTasks').click();await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('版本过旧'));
  page.once('dialog',dialog=>dialog.accept());await page.locator('#tasks').getByRole('button',{name:'运行',exact:true}).first().click();
  await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('未提交'));
  assert.equal(unexpectedRuns,0);
  assert.deepEqual(errors,[]);console.log('PASS：任务分页搜索、菜单轮询、目录浏览、多组增删、未保存确认、保存、演练、日志分页筛选、真实复制、复制配置、删除取消、窄屏布局、无脚本异常');
 }catch(error){if(browser){const p=browser.contexts()[0]?.pages()[0];if(p){await p.screenshot({path:'/tmp/sync-ui-failure.png',fullPage:true});console.error((await p.locator('body').innerText()).slice(0,5000));console.error('脚本状态',await p.evaluate(()=>({errors:document.querySelector('#folderError').textContent,address:document.querySelector('#folderAddress').value})))}}throw error
 }finally{if(browser)await browser.close();server.kill('SIGTERM');await new Promise(resolve=>{server.once('exit',resolve);if(server.exitCode!==null)resolve()});fs.rmSync(temp,{recursive:true,force:true})}
})().catch(error=>{console.error(error);process.exitCode=1});
